# Injects f_auto (best format per browser — WebP/AVIF/JPEG) and q_auto
# (adaptive quality) into every URL generated by the ActiveStorage
# Cloudinary adapter for image content. Skips PDFs and other non-image
# content types where these transformations would corrupt delivery
# (Cloudinary would rasterize a PDF if served with f_auto).
#
# Critical: when the gem's `download`/`download_chunk` methods call
# `url(key)` internally to fetch the original for variant processing,
# we MUST skip the transforms — otherwise Cloudinary returns the
# transformed bytes (e.g. WebP), the MD5 doesn't match the stored
# checksum of the original PNG/JPEG, and ActiveStorage raises
# IntegrityError. That breaks every variant URL (BO thumbnails, etc.)
# and re-downloads the full original from Cloudinary on every failed
# attempt, burning bandwidth.

return unless Rails.application.config.active_storage.service == :cloudinary

# Defer the patch to after the app is initialized. At initializer load
# time, ActiveStorage::Blob is not yet autoloaded, and the cloudinary
# gem's adapter file references it at the top level — requiring it here
# blows up `assets:precompile` with NameError. By after_initialize the
# adapter has been required by ActiveStorage during service registration,
# so the constant is defined and we can safely prepend.
Rails.application.config.after_initialize do
  next unless defined?(ActiveStorage::Service::CloudinaryService)

  module CloudinaryServiceAutoFormat
    SKIP_KEY = :cloudinary_skip_auto_transforms

    def url(key, filename: nil, content_type: "", **options)
      if image_content?(key, content_type) && !Thread.current[SKIP_KEY]
        options[:fetch_format] = :auto unless options.key?(:fetch_format)
        options[:quality] = :auto unless options.key?(:quality)
      end
      super(key, filename: filename, content_type: content_type, **options)
    end

    def download(key, &block)
      with_skipped_transforms { super }
    end

    def download_chunk(key, range)
      with_skipped_transforms { super }
    end

    private

    def with_skipped_transforms
      previous = Thread.current[SKIP_KEY]
      Thread.current[SKIP_KEY] = true
      yield
    ensure
      Thread.current[SKIP_KEY] = previous
    end

    def image_content?(key, content_type)
      ct = content_type.presence
      ct ||= key.respond_to?(:attributes) ? key.attributes[:content_type] : nil
      ct.to_s.start_with?("image/")
    end
  end

  ActiveStorage::Service::CloudinaryService.prepend(CloudinaryServiceAutoFormat)
end
